name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating your first issue. We appreciate your help in making this project better. We will look into it, and get back to you soon."
        pr-message: "Thank you for contributing to this project. This is your first pull request and we are so glad to have you onboard. We will review the request and get back to you soon."
